---
 - name: install required packages
   apt: name={{ item }} update_cache=yes state=latest
   when: ansible_os_family == "Debian"
   tags: not_in_dry_run
   with_items:
    - qemu
    - qemu-utils
    - libvirt-bin
    - bridge-utils

 - name: make sure qemu backup directory exists
   file: path="{{ qemu_backup }}" state=directory

 - name: enable iommu support
   template: src=grub dest=/etc/default/grub
   notify: rebuild grub
   when: qemu_iommu_support != ""
