---
 - name: install required packages for nginx
   action: apt pkg={{ item }} state=present
   with_items:
    - nginx

 - name: copy nginx configuration
   template: src=site dest=/etc/nginx/sites-available/{{ item.site_name }}
   with_items: "{{ sites }}"
   notify: reload nginx
   tags:
    - config

 - name: create sites-enabled symlink
   file: src=/etc/nginx/sites-available/{{ item.site_name }} dest=/etc/nginx/sites-enabled/{{ item.site_name }} state=link
   with_items: "{{ sites }}"

 - name: disable nginx default site
   file:
     path: /etc/nginx/sites-enabled/default
     state: absent
   notify: reload nginx

 - name: Create www directory if it doesn't exist
   file: path="{{ www_root }}/{{ item.site_name }}" state=directory mode="{{ www_permissions }}"
   with_items: "{{ sites }}"

 - name: set permissions on www-root
   file: path={{ www_root }} owner="{{ www_root_owner }}" group="{{ www_root_group }}" recurse=true

 - include: php.yml
   when: "{{ item.php | default(False) }}"
   with_items: "{{ sites }}"

 - include: ssl.yml
   when: "{{ item.ssl | default(False) }}"
   with_items: "{{ sites }}"
