---
 - include: ubuntu.yml
   when: ansible_os_family == "Debian"

 - include: freebsd.yml
   when: ansible_os_family == "FreeBSD"

 - name: Create www directory if it doesn't exist
   file: path="{{ www_root }}/{{ item.site_name }}" state=directory mode="{{ www_permissions }}"
   with_items: "{{ sites }}"

 - name: set permissions on www-root
   file: path={{ www_root }} owner="{{ nginx_user }}" group="{{ nginx_group }}" recurse=true

 - include: ubuntu-php.yml
   when: "item.php | default(False) and ansible_os_family == 'Debian'"
   with_items: "{{ sites }}"

 - include: freebsd-php.yml
   when: "item.php | default(False) and ansible_os_family == 'FreeBSD'"
   with_items: "{{ sites }}"

 - include: ubuntu-ssl.yml
   when: "item.ssl | default(False) and ansible_os_family == 'Debian'"
   with_items: "{{ sites }}"
