---
 - name: download dokuwiki source
   get_url:
     url: http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
     dest: "{{ dokuwiki_cache }}"
   register: dokuwiki_download

 - name: extract dokuwiki
   unarchive:
     src: "{{ dokuwiki_cache }}"
     dest: "{{ www_root }}"
     copy: no
     extra_opts:
       - "--strip-components=1"
   when: dokuwiki_download.changed
   notify: set permissions on www-root

 - name: setup .htaccess file
   file: src="{{ www_root }}/.htaccess.dist" dest="{{ www_root }}/.htaccess" state=link

 - name: remove messages cache
   file: path="{{ www_root }}/data/cache/messages.txt" state=absent
