---
packages_arch:
 - tmux
 - vim
 - postfix
 - openssh

packages_ubuntu:
 - tmux
 - vim
 - aptitude
 - rsync
 - postfix
 - bsd-mailx
 - ntp
 - unattended-upgrades
 - fail2ban
 - lsof
 - strace
 - atop
 - wget

packages_removed_ubuntu:
 - whoopsie
 - apport
 - apport-hooks-medibuntu
 - apport-symptoms
 - python-apport
 - mlocate

use_nfs: True

all_public_keys: "{{ public_key | union(my_public_keys | default([])) }}"

postfix_config: "postfix_main.cf.j2"
postfix_interfaces: "loopback-only"
unattended_upgrades_template: "50unattended_upgrades.j2"
notification_email: "root@localhost.localdomain"

# place your public SSH key here (or override in group_vars/all)
public_key: []
