---
 - include: ubuntu.yml
   when: ansible_os_family == "Debian"

 - include: freebsd.yml
   when: ansible_os_family == "FreeBSD"

 - name: create www-root
   file: path={{ www_root }} owner={{ apache2_user }} group={{ apache2_group }} state=directory recurse=yes
   when: create_www_root

 - name: create php temp dir
   file: path={{ php_tmp }} owner={{ apache2_user }} group={{ apache2_group }} state=directory recurse=yes

 - name: copy apache2 config
   template: src={{ apache2_config }} dest={{ apache2_config_dest }}
   notify: reload apache2

 - name: copy php.ini
   template: src={{ php_config }} dest={{ php_config_dest }}
   notify:
    - reload apache2

 - name: enable apache2 modules
   apache2_module: name={{ item }} state=present
   with_items: "{{ apache2_modules }}"
   notify: restart apache2
