---
 - name: install common packages (Arch)
   pacman: name={{ item }} update_cache=yes
   with_items: packages_arch
   when: ansible_os_family == "Archlinux"

 - name: install common packages (Ubuntu)
   apt: name={{ item }} update_cache=yes
   with_items: packages_ubuntu
   when: ansible_os_family == "Debian"

 - name: add amartin@garibaldi's authorized key
   authorized_key: user=root key="{{ item }}"
   with_file:
    - amartin.pub
