---
 - name: check if git checkout exists already
   command: ls "{{ www_root }}/.git"
   register: ls
   failed_when: false

 - name: clean up www before git checkout
   file: path="{{ www_root }}" state=absent
   when: ls.rc != 0 

 - name: deploy app to www-root
   git: repo="{{ server_repo }}" force=yes dest="{{ www_root }}" accept_hostkey=yes
   tags:
    - config

 - name: generate config.php
   template: src=config.php dest="{{ www_root }}/config.php" owner=www-data group=www-data
   tags:
    - config
