---
 - name: Add Oracle Java PPA
   apt_repository: repo="ppa:webupd8team/java"

 - name: Automatically select the Oracle License
   shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
   changed_when: false

 - name: Install Oracle Java
   apt: pkg=oracle-java7-installer update-cache=yes state=latest

 - name: download madsonic
   get_url: url="{{ madsonic_url }}" dest=/tmp

 - name: install madsonic
   apt: deb="/tmp/{{ madsonic_deb }}"
   notify: restart madsonic

 - name: create madsonic user
   user: name={{ madsonic_user }} home={{ madsonic_home }} shell=/bin/false system=yes

 - name: set permissions on music directory
   file: path={{ madsonic_music_dir }} owner=madsonic recurse=true state=directory

 - name: set madsonic settings
   template: src=madsonic.j2 dest=/etc/default/madsonic
   notify: restart madsonic

 - name: remove temporary files
   file: path="/tmp/{{ madsonic_deb }}" state=absent
   changed_when: False
