---
 - name: add lwp apt key
   apt_key: url="https://packagecloud.io/gpg.key" validate_certs=False

 - name: add repositories
   apt_repository: repo="{{ item }}"
   with_items:
    - "ppa:ubuntu-lxc/lxc-stable"
    - "deb https://packagecloud.io/claudyus/LXC-Web-Panel/ubuntu/ {{ ansible_distribution_release }} main"

 - name: add requirements for installing packages over HTTPS
   apt: name=apt-transport-https update_cache=yes cache_valid_time="{{ apt_cache_time }}" state=latest
   tags: not_in_dry_run

 - name: add flask repository for precise
   apt_repository: repo="ppa:openstack-ubuntu-testing/icehouse"
   when: ansible_distribution_release == "precise"

 - name: install required packages
   apt: name={{ item }} update_cache=yes cache_valid_time="{{ apt_cache_time }}" state=latest
   when: ansible_os_family == "Debian"
   tags: not_in_dry_run
   with_items:
    - lxc
    - lwp
    - python-flask
    - python-pam
    - bridge-utils
    - nmap

 - name: configure apparmor
   template: src=container-base.j2 dest=/etc/apparmor.d/abstractions/lxc/container-base
   notify: restart apparmor

 - name: make sure lxc backup directory exists
   file: path="{{ lxc_backup }}" state=directory

 - name: update lxc config
   template: src=default.conf.j2 dest=/etc/lxc/default.conf
   notify: restart lxc
   tags:
    - config

 - name: configure lwp
   template: src=lwp.conf.j2 dest=/etc/lwp/lwp.conf
   notify: restart lwp
   tags:
    - config
