---
 - name: install required packages
   apt: name={{ item }} update_cache=yes
   when: ansible_os_family == "Debian"
   with_items: git_packages

 - name: create gitbucket directories
   file: path={{ item }} state=directory
   with_items:
    - "{{ gitbucket_dir }}"
    - "{{ gitbucket_home }}/tmp"

 - name: download gitbucket
   get_url: url=https://github.com/takezoe/gitbucket/releases/download/{{ gitbucket_version }}/gitbucket.war dest={{ gitbucket_dir }}

 - name: copy gitbucket upstart job
   template: src=gitbucket.conf.j2 dest=/etc/init/gitbucket.conf
   notify: restart gitbucket
