---
 - name: install required packages
   apt: name={{ item }} update_cache=yes cache_valid_time="{{ apt_cache_time }}" state=latest
   when: ansible_os_family == "Debian"
   tags: not_in_dry_run
   with_items:
    - bridge-utils

 - name: configure network interfaces
   template: src=interfaces.j2 dest=/etc/network/interfaces
   notify: restart networking

 - name: configure iptables rules
   template: src="iptables.rules" dest="{{ iptables_file }}"
   when: iptables_rules != ""
   notify: reload iptables
