---
 - include: ubuntu.yml
   when: ansible_os_family == "Debian"

 - include: arch.yml
   when: ansible_os_family == "ArchLinux"

 - include: freebsd.yml
   when: ansible_os_family == "FreeBSD"

 - name: add authorized key
   authorized_key: user=root key="{{ item }}"
   when: public_key != "" and ansible_os_family != "ArchLinux"
   with_items: "{{ all_public_keys }}"

 - name: setup smart to monitor drives
   template: src={{ item.src }} dest={{ item.dest }}
   with_items:
    - { src: smartmontools.j2, dest: /etc/default/smartmontools, when: "{{ ansible_os_family == 'Debian' }}" }
    - { src: smartd.conf.j2, dest: "{{ conf_dir }}/smartd.conf" }
   when: use_smart and item.when|default(True)
   notify:
     - restart smartmontools
     - restart smartd

 - name: configure postfix
   template: src={{ postfix_config }} dest="{{ conf_dir }}/postfix/main.cf"
   notify: restart postfix

 - name: copy scripts
   template: src="{{ item.name }}" dest="/usr/local/bin/{{ item.name }}" mode=0755
   with_items:
    - { name: avidlib.sh }

 - include: backup_client.yml
   when: backup_client
