---
 - include: ubuntu.yml                     
   when: ansible_os_family == "Debian"     

 - include: freebsd.yml                    
   when: ansible_os_family == "FreeBSD"

 - name: create sanoid directories
   file: path={{ item }} state=directory
   with_items:
     - "{{ conf_dir }}/sanoid"
     - /var/cache/sanoid
 
 - name: download sanoid
   get_url: url=https://github.com/jimsalterjrs/sanoid/archive/v{{ sanoid_version }}.tar.gz dest=/var/cache/sanoid/{{ sanoid_version }}.tar.gz
   register: sanoid_update

 - name: extract sanoid
   unarchive: src=/var/cache/sanoid/{{ sanoid_version }}.tar.gz dest=/var/cache/sanoid copy=no
   when: sanoid_update.changed
   notify: update sanoid

 - name: copy sanoid config file
   template: src=sanoid.conf dest="{{ conf_dir }}/sanoid/sanoid.conf"

 - name: schedule sanoid cron
   cron: name="run sanoid backup" job="/usr/local/bin/sanoid --cron"

 - name: set /etc/exportfs
   template: src=exports.j2 dest=/etc/exports
   notify:
     - reload nfs exports ubuntu
     - reload nfs exports freebsd
   when: configure_exports

