---
gogs_storage: /mnt/storage
gogs_backup: "{{ gogs_storage }}/backup"

gogs_backup_keeptime: 60

gogs_db_name: "gogs"
gogs_db_user: "gogs"
gogs_db_pass: "examplePassword"
gogs_secret: "exampleSecret"
